site_name: Aura Documentation
site_description: Documentation for Aura - Agent for Understanding, Reasoning and Automation
site_author: Sentientia
repo_url: https://github.com/Sentientia/Aura
repo_name: Sentientia/Aura

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link

nav:
  - Home: index.md
  - Installation: installation.md
  - Architecture: architecture.md
  - Agents:
    - Overview: agents/index.md
    - Chat Agent: agents/chat_agent.md
    - QA Agent: agents/qa_agent.md
  - Actions:
    - Overview: actions/index.md
    - Chat Action: actions/chat_action.md
    - Web Search Action: actions/web_search_action.md
    - Calendar Action: actions/calendar_action.md
    - Email Action: actions/email_action.md
    - Contact Action: actions/contact_action.md
    - Answer Action: actions/answer_action.md
  - UI: ui.md
  - Contributing: contributing.md
  - Documentation Development: docs_development.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist
  - admonition
  - toc:
      permalink: true

plugins:
  - search
