from enum import Enum

class Mode(Enum):   
    TEXT_2_TEXT_CASCADED = "TEXT_2_TEXT_CASCADED"
    TEXT_2_SPEECH_CASCADED = "TEXT_2_SPEECH_CASCADED"
    SPEECH_2_TEXT_CASCADED = "SPEECH_2_TEXT_CASCADED"
    SPEECH_2_SPEECH_CASCADED = "SPEECH_2_SPEECH_CASCADED"

    #Operation modes
    UI = "UI"
    QA_EVAL = "QA_EVAL"