#Exp_name to be changed in 2 places

output_dir: /data/tir/projects/tir7/user_data/lmaben/llm-weights/outputs/llamafactory/llmfac_qwen2_5_1_5b_instruct-full-lr1e-6-24kcontext-grad_accum32

model_name_or_path: Qwen/Qwen2.5-1.5B-Instruct

stage: sft
do_train: true
finetuning_type: full
deepspeed: examples/deepspeed/ds_z2_config.json

dataset: code_edit_train
template: qwen
cutoff_len: 10500
overwrite_cache: true
preprocessing_num_workers: 16

logging_steps: 5
save_steps: 50
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 4
learning_rate: 1.0e-6
num_train_epochs: 2.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
eval_dataset: code_edit_val
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 15

report_to: wandb
run_name: llmfac_qwen2_5_1_5b_instruct-full-lr1e-6-24kcontext-grad_accum32